"""YAML configuration loader.

The framework keeps every threshold, hyperparameter and reference value in
``config/*.yaml``.  Loading them via :func:`load_config` ensures the manuscript
tables can be regenerated by editing one file.
"""
from __future__ import annotations

from functools import lru_cache
from pathlib import Path
from typing import Any, Dict

import yaml


def project_config_dir() -> Path:
    """Resolve the absolute path to the bundled ``config/`` directory."""
    return Path(__file__).resolve().parents[2] / "config"


@lru_cache(maxsize=None)
def load_config(name: str) -> Dict[str, Any]:
    """Load a YAML config file by short name (without extension).

    Parameters
    ----------
    name : str
        e.g. ``"thresholds"``, ``"reference_doses"``, ``"hyperparameters"``,
        ``"exposure_parameters"``, ``"study_area"``.

    Returns
    -------
    dict
        Parsed YAML.  Cached for the life of the process.
    """
    path = project_config_dir() / f"{name}.yaml"
    if not path.exists():                                # pragma: no cover
        raise FileNotFoundError(path)
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)
